'\" t
.\"     Title: rebirthdb
.\"    Author: Bill Rowan
.\"      Date: 2012/11/08
.\"    Manual: RebirthDB Manual
.\"    Source: RebirthDB 0.1
.\"  Language: English
.\"
.TH "REBIRTHDB" "1" "CURRENT_DATE" "RebirthDB SHORT_VERSION" "RebirthDB Manual"
.SH "NAME"
rebirthdb \- an open source distributed database system
.sp
.SH "DESCRIPTION"
.sp
RebirthDB is an open source distributed database system featuring automatic query parallelization, a powerful query language, and friendly administrative tools. Please run \fI\fBrebirthdb\fR \-\-help for full usage information
